# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - '*'
    exclude:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'FrontEndTests/FrontEndTests/FrontEndTests.csproj'
    feedsToUse: 'select'
    vstsFeed: 'd728bbca-18db-44f0-917c-0f16adc5711f'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FrontEndTests/FrontEndTests/FrontEndTests.csproj'
- task: DotNetCoreCLI@2
  inputs:
      command: 'test'
      projects: 'FrontEndTests/FrontEndTests/FrontEndTests.csproj'